# Project: Game
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = ../obj/Game/Game_private.res
OBJ      = ../obj/Game/Human.o ../obj/Game/GameState.o ../obj/Game/Settings.o ../obj/Game/World.o ../obj/Game/ParticleSystem.o ../obj/Game/main.o ../obj/Game/Zombie.o ../obj/Game/TaskScheduler.o ../obj/Game/Random.o ../obj/Game/Render.o ../obj/Game/Cursor.o ../obj/Game/Font.o ../obj/Game/Http.o ../obj/Game/Image.o ../obj/Game/InstanceLock.o ../obj/Game/Log.o ../obj/Game/Process.o ../obj/Game/String.o ../obj/Game/TextInput.o ../obj/Game/Audio.o ../obj/Game/Network.o ../obj/Game/Blur.o ../obj/Game/Menu.o ../obj/Game/GameNetwork.o ../obj/Game/GameRenderer.o ../obj/Game/GameMenu.o ../obj/Game/WorldClient.o ../obj/Game/WorldGrid.o ../obj/Game/WorldEntity.o $(RES)
LINKOBJ  = ../obj/Game/Human.o ../obj/Game/GameState.o ../obj/Game/Settings.o ../obj/Game/World.o ../obj/Game/ParticleSystem.o ../obj/Game/main.o ../obj/Game/Zombie.o ../obj/Game/TaskScheduler.o ../obj/Game/Random.o ../obj/Game/Render.o ../obj/Game/Cursor.o ../obj/Game/Font.o ../obj/Game/Http.o ../obj/Game/Image.o ../obj/Game/InstanceLock.o ../obj/Game/Log.o ../obj/Game/Process.o ../obj/Game/String.o ../obj/Game/TextInput.o ../obj/Game/Audio.o ../obj/Game/Network.o ../obj/Game/Blur.o ../obj/Game/Menu.o ../obj/Game/GameNetwork.o ../obj/Game/GameRenderer.o ../obj/Game/GameMenu.o ../obj/Game/WorldClient.o ../obj/Game/WorldGrid.o ../obj/Game/WorldEntity.o $(RES)
LIBS     = -L"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/lib" -static-libgcc -L"../libs/enet/lib" -L"../libs/SDL2/lib" -L"../libs/SDL2_ttf/lib" -L"../libs/curl/lib" -L"../libs/SDL2_mixer/lib" -L"../libs/SDL2_image/lib" -L"../libs/lz4/lib" -mwindows -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf -lSDL2_image -lSDL2_mixer -lcurl -lenet -lws2_32 -lwinmm -lgdi32 -lSDL2_ttf -lSDL2_mixer -lSDL2_image -llz4 -s
INCS     = -I"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/include" -I"../libs/enet/include" -I"../libs/SDL2/include/SDL2" -I"../libs/SDL2_ttf/include/SDL2" -I"../libs/FastNoiseLite" -I"../common" -I"../libs/curl/include" -I"../libs/SDL2_mixer/include/SDL2" -I"../libs/SDL2_image/include/SDL2" -I"../libs/nlohmann" -I"." -I"../libs/lz4/include"
CXXINCS  = -I"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/include" -I"../libs/enet/include" -I"../libs/SDL2/include/SDL2" -I"../libs/SDL2_ttf/include/SDL2" -I"../libs/FastNoiseLite" -I"../common" -I"../libs/curl/include" -I"../libs/SDL2_mixer/include/SDL2" -I"../libs/SDL2_image/include/SDL2" -I"../libs/nlohmann" -I"." -I"../libs/lz4/include"
BIN      = ../release/Game.exe
CXXFLAGS = $(CXXINCS) -ansi -O2 -std=c++11 -pipe -DGAME_BUILD -finput-charset=GBK -fexec-charset=UTF-8
CFLAGS   = $(INCS) -ansi -O2 -std=c++11 -pipe
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../obj/Game/Human.o: ../common/Human.cpp
	$(CPP) -c ../common/Human.cpp -o ../obj/Game/Human.o $(CXXFLAGS)

../obj/Game/GameState.o: GameState.cpp
	$(CPP) -c GameState.cpp -o ../obj/Game/GameState.o $(CXXFLAGS)

../obj/Game/Settings.o: ../common/Settings.cpp
	$(CPP) -c ../common/Settings.cpp -o ../obj/Game/Settings.o $(CXXFLAGS)

../obj/Game/World.o: ../common/World.cpp
	$(CPP) -c ../common/World.cpp -o ../obj/Game/World.o $(CXXFLAGS)

../obj/Game/ParticleSystem.o: ../common/ParticleSystem.cpp
	$(CPP) -c ../common/ParticleSystem.cpp -o ../obj/Game/ParticleSystem.o $(CXXFLAGS)

../obj/Game/main.o: main.cpp
	$(CPP) -c main.cpp -o ../obj/Game/main.o $(CXXFLAGS)

../obj/Game/Zombie.o: ../common/Zombie.cpp
	$(CPP) -c ../common/Zombie.cpp -o ../obj/Game/Zombie.o $(CXXFLAGS)

../obj/Game/TaskScheduler.o: ../common/TaskScheduler.cpp
	$(CPP) -c ../common/TaskScheduler.cpp -o ../obj/Game/TaskScheduler.o $(CXXFLAGS)

../obj/Game/Random.o: ../common/Tool/Random.cpp
	$(CPP) -c ../common/Tool/Random.cpp -o ../obj/Game/Random.o $(CXXFLAGS)

../obj/Game/Render.o: ../common/Tool/Render.cpp
	$(CPP) -c ../common/Tool/Render.cpp -o ../obj/Game/Render.o $(CXXFLAGS)

../obj/Game/Cursor.o: ../common/Tool/Cursor.cpp
	$(CPP) -c ../common/Tool/Cursor.cpp -o ../obj/Game/Cursor.o $(CXXFLAGS)

../obj/Game/Font.o: ../common/Tool/Font.cpp
	$(CPP) -c ../common/Tool/Font.cpp -o ../obj/Game/Font.o $(CXXFLAGS)

../obj/Game/Http.o: ../common/Tool/Http.cpp
	$(CPP) -c ../common/Tool/Http.cpp -o ../obj/Game/Http.o $(CXXFLAGS)

../obj/Game/Image.o: ../common/Tool/Image.cpp
	$(CPP) -c ../common/Tool/Image.cpp -o ../obj/Game/Image.o $(CXXFLAGS)

../obj/Game/InstanceLock.o: ../common/Tool/InstanceLock.cpp
	$(CPP) -c ../common/Tool/InstanceLock.cpp -o ../obj/Game/InstanceLock.o $(CXXFLAGS)

../obj/Game/Log.o: ../common/Tool/Log.cpp
	$(CPP) -c ../common/Tool/Log.cpp -o ../obj/Game/Log.o $(CXXFLAGS)

../obj/Game/Process.o: ../common/Tool/Process.cpp
	$(CPP) -c ../common/Tool/Process.cpp -o ../obj/Game/Process.o $(CXXFLAGS)

../obj/Game/String.o: ../common/Tool/String.cpp
	$(CPP) -c ../common/Tool/String.cpp -o ../obj/Game/String.o $(CXXFLAGS)

../obj/Game/TextInput.o: ../common/Tool/TextInput.cpp
	$(CPP) -c ../common/Tool/TextInput.cpp -o ../obj/Game/TextInput.o $(CXXFLAGS)

../obj/Game/Audio.o: ../common/Tool/Audio.cpp
	$(CPP) -c ../common/Tool/Audio.cpp -o ../obj/Game/Audio.o $(CXXFLAGS)

../obj/Game/Network.o: ../common/Network.cpp
	$(CPP) -c ../common/Network.cpp -o ../obj/Game/Network.o $(CXXFLAGS)

../obj/Game/Blur.o: ../common/Tool/Blur.cpp
	$(CPP) -c ../common/Tool/Blur.cpp -o ../obj/Game/Blur.o $(CXXFLAGS)

../obj/Game/Menu.o: ../common/Tool/Menu.cpp
	$(CPP) -c ../common/Tool/Menu.cpp -o ../obj/Game/Menu.o $(CXXFLAGS)

../obj/Game/GameNetwork.o: GameNetwork.cpp
	$(CPP) -c GameNetwork.cpp -o ../obj/Game/GameNetwork.o $(CXXFLAGS)

../obj/Game/GameRenderer.o: GameRenderer.cpp
	$(CPP) -c GameRenderer.cpp -o ../obj/Game/GameRenderer.o $(CXXFLAGS)

../obj/Game/GameMenu.o: GameMenu.cpp
	$(CPP) -c GameMenu.cpp -o ../obj/Game/GameMenu.o $(CXXFLAGS)

../obj/Game/WorldClient.o: ../common/WorldClient.cpp
	$(CPP) -c ../common/WorldClient.cpp -o ../obj/Game/WorldClient.o $(CXXFLAGS)

../obj/Game/WorldGrid.o: ../common/WorldGrid.cpp
	$(CPP) -c ../common/WorldGrid.cpp -o ../obj/Game/WorldGrid.o $(CXXFLAGS)

../obj/Game/WorldEntity.o: ../common/WorldEntity.cpp
	$(CPP) -c ../common/WorldEntity.cpp -o ../obj/Game/WorldEntity.o $(CXXFLAGS)

../obj/Game/Game_private.res: Game_private.rc 
	$(WINDRES) -i Game_private.rc --input-format=rc -o ../obj/Game/Game_private.res -O coff 

