# Project: Server
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = ../obj/Server/Server_private.res
OBJ      = ../obj/Server/Human.o ../obj/Server/main.o ../obj/Server/Settings.o ../obj/Server/World.o ../obj/Server/Zombie.o ../obj/Server/TaskScheduler.o ../obj/Server/Random.o ../obj/Server/String.o ../obj/Server/Log.o ../obj/Server/Network.o ../obj/Server/WorldEntity.o ../obj/Server/WorldGrid.o $(RES)
LINKOBJ  = ../obj/Server/Human.o ../obj/Server/main.o ../obj/Server/Settings.o ../obj/Server/World.o ../obj/Server/Zombie.o ../obj/Server/TaskScheduler.o ../obj/Server/Random.o ../obj/Server/String.o ../obj/Server/Log.o ../obj/Server/Network.o ../obj/Server/WorldEntity.o ../obj/Server/WorldGrid.o $(RES)
LIBS     = -L"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/lib" -static-libgcc -L"../libs/enet/lib" -L"../libs/lz4/lib" -L"../libs/curl/lib" -mconsole -lmingw32 -lenet -lws2_32 -lwinmm -llz4 -lcurl -s
INCS     = -I"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/include" -I"../libs/enet/include" -I"../common" -I"../libs/FastNoiseLite" -I"../libs/SDL2/include/SDL2" -I"../libs/lz4/include" -I"../libs/nlohmann" -I"../libs/curl/include"
CXXINCS  = -I"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/include" -I"../libs/enet/include" -I"../common" -I"../libs/FastNoiseLite" -I"../libs/SDL2/include/SDL2" -I"../libs/lz4/include" -I"../libs/nlohmann" -I"../libs/curl/include"
BIN      = ../release/Server.exe
CXXFLAGS = $(CXXINCS) -ansi -O2 -std=c++11 -pipe -DSERVER_BUILD -finput-charset=GBK -fexec-charset=UTF-8
CFLAGS   = $(INCS) -ansi -O2 -std=c++11 -pipe
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../obj/Server/Human.o: ../common/Human.cpp
	$(CPP) -c ../common/Human.cpp -o ../obj/Server/Human.o $(CXXFLAGS)

../obj/Server/main.o: main.cpp
	$(CPP) -c main.cpp -o ../obj/Server/main.o $(CXXFLAGS)

../obj/Server/Settings.o: ../common/Settings.cpp
	$(CPP) -c ../common/Settings.cpp -o ../obj/Server/Settings.o $(CXXFLAGS)

../obj/Server/World.o: ../common/World.cpp
	$(CPP) -c ../common/World.cpp -o ../obj/Server/World.o $(CXXFLAGS)

../obj/Server/Zombie.o: ../common/Zombie.cpp
	$(CPP) -c ../common/Zombie.cpp -o ../obj/Server/Zombie.o $(CXXFLAGS)

../obj/Server/TaskScheduler.o: ../common/TaskScheduler.cpp
	$(CPP) -c ../common/TaskScheduler.cpp -o ../obj/Server/TaskScheduler.o $(CXXFLAGS)

../obj/Server/Random.o: ../common/Tool/Random.cpp
	$(CPP) -c ../common/Tool/Random.cpp -o ../obj/Server/Random.o $(CXXFLAGS)

../obj/Server/String.o: ../common/Tool/String.cpp
	$(CPP) -c ../common/Tool/String.cpp -o ../obj/Server/String.o $(CXXFLAGS)

../obj/Server/Log.o: ../common/Tool/Log.cpp
	$(CPP) -c ../common/Tool/Log.cpp -o ../obj/Server/Log.o $(CXXFLAGS)

../obj/Server/Network.o: ../common/Network.cpp
	$(CPP) -c ../common/Network.cpp -o ../obj/Server/Network.o $(CXXFLAGS)

../obj/Server/WorldEntity.o: ../common/WorldEntity.cpp
	$(CPP) -c ../common/WorldEntity.cpp -o ../obj/Server/WorldEntity.o $(CXXFLAGS)

../obj/Server/WorldGrid.o: ../common/WorldGrid.cpp
	$(CPP) -c ../common/WorldGrid.cpp -o ../obj/Server/WorldGrid.o $(CXXFLAGS)

../obj/Server/Server_private.res: Server_private.rc 
	$(WINDRES) -i Server_private.rc --input-format=rc -o ../obj/Server/Server_private.res -O coff 

