/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef EDITOR_PRIVATE_H
#define EDITOR_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.2.0"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	2
#define VER_BUILD	0
#define COMPANY_NAME	"alien547"
#define FILE_VERSION	"1.0.2.0"
#define FILE_DESCRIPTION	""
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	"Copyright (c) 2026 alien547"
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	"Editor"
#define PRODUCT_VERSION	"1.0.2.0"

#endif /*EDITOR_PRIVATE_H*/
