# Project: Editor
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = ../obj/Editor/Editor_private.res
OBJ      = ../obj/Editor/main.o ../obj/Editor/Settings.o ../obj/Editor/World.o ../obj/Editor/Zombie.o ../obj/Editor/Human.o ../obj/Editor/ParticleSystem.o ../obj/Editor/TaskScheduler.o ../obj/Editor/Audio.o ../obj/Editor/Font.o ../obj/Editor/Log.o ../obj/Editor/Render.o ../obj/Editor/String.o ../obj/Editor/TextInput.o ../obj/Editor/Random.o ../obj/Editor/Blur.o ../obj/Editor/Image.o ../obj/Editor/Menu.o ../obj/Editor/WorldClient.o ../obj/Editor/WorldEntity.o ../obj/Editor/WorldGrid.o ../obj/Editor/Form.o $(RES)
LINKOBJ  = ../obj/Editor/main.o ../obj/Editor/Settings.o ../obj/Editor/World.o ../obj/Editor/Zombie.o ../obj/Editor/Human.o ../obj/Editor/ParticleSystem.o ../obj/Editor/TaskScheduler.o ../obj/Editor/Audio.o ../obj/Editor/Font.o ../obj/Editor/Log.o ../obj/Editor/Render.o ../obj/Editor/String.o ../obj/Editor/TextInput.o ../obj/Editor/Random.o ../obj/Editor/Blur.o ../obj/Editor/Image.o ../obj/Editor/Menu.o ../obj/Editor/WorldClient.o ../obj/Editor/WorldEntity.o ../obj/Editor/WorldGrid.o ../obj/Editor/Form.o $(RES)
LIBS     = -L"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/lib" -static-libgcc -L"../libs/SDL2/lib" -L"../libs/SDL2_ttf/lib" -L"../libs/curl/lib" -L"../libs/SDL2_image/lib" -L"../libs/SDL2_mixer/lib" -L"../libs/lz4/lib" -mwindows -lmingw32 -lSDL2main -lSDL2 -lws2_32 -lwinmm -lgdi32 -lopengl32 -lcurl -lSDL2_ttf -lSDL2_image -lSDL2_mixer -llz4 -s
INCS     = -I"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/include" -I"../libs/SDL2/include/SDL2" -I"../libs/SDL2_ttf/include/SDL2" -I"../common" -I"../libs/curl/include" -I"../libs/SDL2_image/include/SDL2" -I"../libs/SDL2_mixer/include/SDL2" -I"../libs/FastNoiseLite" -I"../libs/lz4/include" -I"../libs/nlohmann"
CXXINCS  = -I"C:/Users/Administrator/Desktop/资料库/Dev-Cpp/MinGW64/include" -I"../libs/SDL2/include/SDL2" -I"../libs/SDL2_ttf/include/SDL2" -I"../common" -I"../libs/curl/include" -I"../libs/SDL2_image/include/SDL2" -I"../libs/SDL2_mixer/include/SDL2" -I"../libs/FastNoiseLite" -I"../libs/lz4/include" -I"../libs/nlohmann"
BIN      = ../release/Editor.exe
CXXFLAGS = $(CXXINCS) -ansi -O2 -std=c++11 -pipe -finput-charset=GBK -fexec-charset=UTF-8 -DEDITOR_BUILD
CFLAGS   = $(INCS) -ansi -O2 -std=c++11 -pipe
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../obj/Editor/main.o: main.cpp
	$(CPP) -c main.cpp -o ../obj/Editor/main.o $(CXXFLAGS)

../obj/Editor/Settings.o: ../common/Settings.cpp
	$(CPP) -c ../common/Settings.cpp -o ../obj/Editor/Settings.o $(CXXFLAGS)

../obj/Editor/World.o: ../common/World.cpp
	$(CPP) -c ../common/World.cpp -o ../obj/Editor/World.o $(CXXFLAGS)

../obj/Editor/Zombie.o: ../common/Zombie.cpp
	$(CPP) -c ../common/Zombie.cpp -o ../obj/Editor/Zombie.o $(CXXFLAGS)

../obj/Editor/Human.o: ../common/Human.cpp
	$(CPP) -c ../common/Human.cpp -o ../obj/Editor/Human.o $(CXXFLAGS)

../obj/Editor/ParticleSystem.o: ../common/ParticleSystem.cpp
	$(CPP) -c ../common/ParticleSystem.cpp -o ../obj/Editor/ParticleSystem.o $(CXXFLAGS)

../obj/Editor/TaskScheduler.o: ../common/TaskScheduler.cpp
	$(CPP) -c ../common/TaskScheduler.cpp -o ../obj/Editor/TaskScheduler.o $(CXXFLAGS)

../obj/Editor/Audio.o: ../common/Tool/Audio.cpp
	$(CPP) -c ../common/Tool/Audio.cpp -o ../obj/Editor/Audio.o $(CXXFLAGS)

../obj/Editor/Font.o: ../common/Tool/Font.cpp
	$(CPP) -c ../common/Tool/Font.cpp -o ../obj/Editor/Font.o $(CXXFLAGS)

../obj/Editor/Log.o: ../common/Tool/Log.cpp
	$(CPP) -c ../common/Tool/Log.cpp -o ../obj/Editor/Log.o $(CXXFLAGS)

../obj/Editor/Render.o: ../common/Tool/Render.cpp
	$(CPP) -c ../common/Tool/Render.cpp -o ../obj/Editor/Render.o $(CXXFLAGS)

../obj/Editor/String.o: ../common/Tool/String.cpp
	$(CPP) -c ../common/Tool/String.cpp -o ../obj/Editor/String.o $(CXXFLAGS)

../obj/Editor/TextInput.o: ../common/Tool/TextInput.cpp
	$(CPP) -c ../common/Tool/TextInput.cpp -o ../obj/Editor/TextInput.o $(CXXFLAGS)

../obj/Editor/Random.o: ../common/Tool/Random.cpp
	$(CPP) -c ../common/Tool/Random.cpp -o ../obj/Editor/Random.o $(CXXFLAGS)

../obj/Editor/Blur.o: ../common/Tool/Blur.cpp
	$(CPP) -c ../common/Tool/Blur.cpp -o ../obj/Editor/Blur.o $(CXXFLAGS)

../obj/Editor/Image.o: ../common/Tool/Image.cpp
	$(CPP) -c ../common/Tool/Image.cpp -o ../obj/Editor/Image.o $(CXXFLAGS)

../obj/Editor/Menu.o: ../common/Tool/Menu.cpp
	$(CPP) -c ../common/Tool/Menu.cpp -o ../obj/Editor/Menu.o $(CXXFLAGS)

../obj/Editor/WorldClient.o: ../common/WorldClient.cpp
	$(CPP) -c ../common/WorldClient.cpp -o ../obj/Editor/WorldClient.o $(CXXFLAGS)

../obj/Editor/WorldEntity.o: ../common/WorldEntity.cpp
	$(CPP) -c ../common/WorldEntity.cpp -o ../obj/Editor/WorldEntity.o $(CXXFLAGS)

../obj/Editor/WorldGrid.o: ../common/WorldGrid.cpp
	$(CPP) -c ../common/WorldGrid.cpp -o ../obj/Editor/WorldGrid.o $(CXXFLAGS)

../obj/Editor/Form.o: ../common/Tool/Form.cpp
	$(CPP) -c ../common/Tool/Form.cpp -o ../obj/Editor/Form.o $(CXXFLAGS)

../obj/Editor/Editor_private.res: Editor_private.rc 
	$(WINDRES) -i Editor_private.rc --input-format=rc -o ../obj/Editor/Editor_private.res -O coff 

